// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image55":
            case "JOHNNY":return img`
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
.................................bbbbbbbbbbbbbbbbbbbbbbbb.............
................................b666666646664464446444444b............
................................b666664666466444644444444b............
................................b666bbbbbbbbbbbbbbbbbb444b............
.........................bb.....b66b..................b44b............
........................b66b....b66b..................b44b............
........bbbbbbbbbbbbbbbbb66bbbbbb66bbbbbbbbbbbbbbbbbbbbbbbbbb.........
.......b2222222222222222b66b2222b66b2222222222222224222224224bb.......
.......b2222222222222222b66b2222b66b222222222222422222242222242bb.....
........bbbb22bbbbbbbbbbb66bbbbbb66bbbbbbbbbbbbbbbbbbbbbbbbb42424b....
...........b22b.bbbbbbb.b66b....b66bb.....bb.bb.....bbb44b..bb242b....
...........b22bb5555555bb66b....b6b88b...b88b88b...b88b44b....b44b....
...........b22b555555555b66bbbbbb6b88b..b888b888b..b88b44b....b42b....
...........b2b55555555555b66666666b88b.b8888b8888b.b88b444b..b444b....
...........b2b5555bbb5555b66666666b888b88888b88888b888bb44b..b44b.....
.....bb....b2b555b...b555b6bbbbbb6b888888b88b88b888888bb444bb444b.....
....b22b...b2b555b...b555b6b....b6b88888bb88b88bb88888b.b444444b......
....b22b..b22b555b...b555b6b....b6b8888b.b88b88b.b8888b..b44444b......
....b222bb222b5555bbb5555b6b....b6b888b..b88b88b..b888b...b444b.......
....b22222222b55555555555b6b....b6b88b...b88b88b...b88bbbb4444b.......
.....b222222b.b555555555b66b....b6b88b...b88b88b...b88b444444b........
......bb222b...b5555555bb66b....b6b88b...b86b88b...b88b444444b........
........bbb.....bbbbbbb.b66b.....b.bb....b88888b....bbbbbbbbb.........
........................b66b.............b88b86b......................
........................b66b.............b88688b......................
........................b666bbbbbbbbbbbbb888868b......................
........................b6666666686868888688b88b......................
........................b66666666886888688b8888b......................
.........................bbbbbbbbbbbbbbbbbbbbbb.......................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "anim1":return [img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`];
            case "anim2":return [img`
. . . . . . . . . . . . . . 
. . . . . f f f f . . . . . 
. . . f f c f f f f f . . . 
. . f f f c f f f c f f . . 
. . f f c f f f f c c f . . 
. . f c f f f f f f c f . . 
. . f f f f f f f f f f . . 
. . f f f f f f f f f f . . 
. . f f f f f f f f f f . . 
. . . 4 f f f f f f 4 . . . 
. . . . 4 4 4 4 4 4 . . . . 
. . e 4 2 2 2 2 2 2 4 e . . 
. . 4 4 2 2 2 2 2 2 d 4 . . 
. . . . 6 6 6 6 6 6 4 4 . . 
. . . . f f f f f f . . . . 
. . . . f f . . . . . . . . 
`, img`
. . . . . . . . . . . . . . 
. . . . . f f f f . . . . . 
. . . f f c f f f f f . . . 
. . f f f c f f f c f f . . 
. . f f c f f f f c c f . . 
. . f c f f f f f f c f . . 
. . f f f f f f f f f f . . 
. . f f f f f f f f f f . . 
. . f f f f f f f f f f . . 
. . . 4 f f f f f f 4 . . . 
. . . . 4 4 4 4 4 4 . . . . 
. . e 4 2 2 2 2 2 2 4 e . . 
. . 4 d 2 2 2 2 2 2 d 4 . . 
. . 4 4 6 6 6 6 6 6 4 4 . . 
. . . . f f f f f f . . . . 
. . . . f f . . f f . . . . 
`, img`
. . . . . . . . . . . . . . 
. . . . . f f f f . . . . . 
. . . f f c f f f f f . . . 
. . f f f c f f f c f f . . 
. . f f c f f f f c c f . . 
. . f c f f f f f f c f . . 
. . f f f f f f f f f f . . 
. . f f f f f f f f f f . . 
. . f f f f f f f f f f . . 
. . . 4 f f f f f f 4 . . . 
. . . . 4 4 4 4 4 4 . . . . 
. . e 4 2 2 2 2 2 2 4 e . . 
. . 4 d 2 2 2 2 2 2 4 4 . . 
. . 4 4 6 6 6 6 6 6 . . . . 
. . . . f f f f f f . . . . 
. . . . . . . . f f . . . . 
`, img`
. . . . . . . . . . . . . . 
. . . . . f f f f . . . . . 
. . . f f c f f f f f . . . 
. . f f f c f f f c f f . . 
. . f f c f f f f c c f . . 
. . f c f f f f f f c f . . 
. . f f f f f f f f f f . . 
. . f f f f f f f f f f . . 
. . f f f f f f f f f f . . 
. . . 4 f f f f f f 4 . . . 
. . . . 4 4 4 4 4 4 . . . . 
. . e 4 2 2 2 2 2 2 4 e . . 
. . 4 d 2 2 2 2 2 2 d 4 . . 
. . 4 4 6 6 6 6 6 6 4 4 . . 
. . . . f f f f f f . . . . 
. . . . f f . . f f . . . . 
`];
            case "anim3":return [img`
. . . . . f f f f f . . . . 
. . . f f f f f f f f f . . 
. . f f f c f f f f f f . . 
. . f f c f f f c f f f f . 
. f c c f f f c c f f c f . 
. f f f f 4 f f f f c c f . 
. . f f 4 4 f f f f f f f . 
. . . . 4 4 f b f f f f f . 
. . . . 4 4 f 1 4 f f f . . 
. . . . 4 4 4 4 4 f f f . . 
. . . . . 4 4 4 4 e . . . . 
. . . . . 2 2 2 4 4 . . . . 
. . . . . 2 2 2 4 4 . . . . 
. . . . . 6 6 6 6 6 . . . . 
. . . . f f f f f f . . . . 
. . . . f f . . f f . . . . 
`, img`
. . . . . f f f f f . . . . 
. . . f f f f f f f f f . . 
. . f f f c f f f f f f . . 
. . f f c f f f c f f f f . 
. f c c f f f c c f f c f . 
. f f f f 4 f f f f c c f . 
. . f f 4 4 f f f f f f f . 
. . . . 4 4 f b f f f f f . 
. . . . 4 4 f 1 4 f f f . . 
. . . . 4 4 4 4 4 f f f . . 
. . . . . 4 4 4 4 e . . . . 
. . . . . 2 2 2 4 4 . . . . 
. . . . . 2 2 2 4 4 . . . . 
. . . . . 6 6 6 6 6 . . . . 
. . . . . f f f f f . . . . 
. . . . . . f f f . . . . . 
`, img`
. . . . . f f f f f . . . . 
. . . f f f f f f f f f . . 
. . f f f c f f f f f f . . 
. . f f c f f f c f f f f . 
. f c c f f f c c f f c f . 
. f f f f 4 f f f f c c f . 
. . f f 4 4 f f f f f f f . 
. . . . 4 4 f b f f f f f . 
. . . . 4 4 f 1 4 f f f . . 
. . . . 4 4 4 4 4 f f f . . 
. . . . . 4 4 4 4 e . . . . 
. . . . . 2 2 2 4 4 . . . . 
. . . . . 2 2 2 4 4 . . . . 
. . . . . 6 6 6 6 6 . . . . 
. . . . . f f f f f . . . . 
. . . . . f f . f f . . . . 
`, img`
. . . . . f f f f f . . . . 
. . . f f f f f f f f f . . 
. . f f f c f f f f f f . . 
. . f f c f f f c f f f f . 
. f c c f f f c c f f c f . 
. f f f f 4 f f f f c c f . 
. . f f 4 4 f f f f f f f . 
. . . . 4 4 f b f f f f f . 
. . . . 4 4 f 1 4 f f f . . 
. . . . 4 4 4 4 4 f f f . . 
. . . . . 4 4 4 4 e . . . . 
. . . . . 2 2 2 4 4 . . . . 
. . . . . 2 2 2 4 4 . . . . 
. . . . . 6 6 6 6 6 . . . . 
. . . . . f f f f f . . . . 
. . . . . . f f f . . . . . 
`];
            case "anim4":return [img`
. . . . f f f f f . . . . . 
. . f f f f f f f f f . . . 
. . f f f f f f c f f f . . 
. f f f f c f f f c f f . . 
. f c f f c c f f f c c f . 
. f c c f f f f e f f f f . 
. f f f f f f f 4 4 f f f . 
. f f f f f b f 4 4 f f . . 
. . f f f 4 1 f 4 4 . . . . 
. . f f f 4 4 4 4 4 . . . . 
. . . . e 4 4 4 4 . . . . . 
. . . . 4 4 2 2 2 . . . . . 
. . . . 4 4 2 2 2 . . . . . 
. . . . 6 6 6 6 6 . . . . . 
. . . . f f f f f f . . . . 
. . . . f f . . f f . . . . 
`, img`
. . . . f f f f f . . . . . 
. . f f f f f f f f f . . . 
. . f f f f f f c f f f . . 
. f f f f c f f f c f f . . 
. f c f f c c f f f c c f . 
. f c c f f f f e f f f f . 
. f f f f f f f 4 4 f f f . 
. f f f f f b f 4 4 f f . . 
. . f f f 4 1 f 4 4 . . . . 
. . f f f 4 4 4 4 4 . . . . 
. . . . e 4 4 4 4 . . . . . 
. . . . 4 4 2 2 2 . . . . . 
. . . . 4 4 2 2 2 . . . . . 
. . . . 6 6 6 6 6 . . . . . 
. . . . f f f f f . . . . . 
. . . . . f f f . . . . . . 
`, img`
. . . . f f f f f . . . . . 
. . f f f f f f f f f . . . 
. . f f f f f f c f f f . . 
. f f f f c f f f c f f . . 
. f c f f c c f f f c c f . 
. f c c f f f f e f f f f . 
. f f f f f f f 4 4 f f f . 
. f f f f f b f 4 4 f f . . 
. . f f f 4 1 f 4 4 . . . . 
. . f f f 4 4 4 4 4 . . . . 
. . . . e 4 4 4 4 . . . . . 
. . . . 4 4 2 2 2 . . . . . 
. . . . 4 4 2 2 2 . . . . . 
. . . . 6 6 6 6 6 . . . . . 
. . . . f f f f f . . . . . 
. . . . f f . f f . . . . . 
`, img`
. . . . f f f f f . . . . . 
. . f f f f f f f f f . . . 
. . f f f f f f c f f f . . 
. f f f f c f f f c f f . . 
. f c f f c c f f f c c f . 
. f c c f f f f e f f f f . 
. f f f f f f f 4 4 f f f . 
. f f f f f b f 4 4 f f . . 
. . f f f 4 1 f 4 4 . . . . 
. . f f f 4 4 4 4 4 . . . . 
. . . . e 4 4 4 4 . . . . . 
. . . . 4 4 2 2 2 . . . . . 
. . . . 4 4 2 2 2 . . . . . 
. . . . 6 6 6 6 6 . . . . . 
. . . . f f f f f . . . . . 
. . . . . f f f . . . . . . 
`];
            case "anim5":return [img`
. . . . . . . . . . . . . . 
. . . . . f f f f . . . . . 
. . . f f f f f c f f . . . 
. . f f c f f f c f f f . . 
. . f c c f f f f c f f . . 
. . f c f f e e f f c f . . 
. . f f f 4 4 e e f f f . . 
. . f f d f 4 4 f d f f . . 
. . f 4 1 f 4 4 f 1 4 f . . 
. . . 4 4 4 4 4 4 4 4 . . . 
. . f e 4 4 4 4 4 4 . . . . 
. . 4 d d e 2 2 2 b 4 e . . 
. . e d d e 2 2 2 2 d 4 . . 
. . . e e f 6 6 6 6 4 4 . . 
. . . . f f f f f f . . . . 
. . . . f f . . . . . . . . 
`, img`
. . . . . . . . . . . . . . 
. . . . . f f f f . . . . . 
. . . f f f f f c f f . . . 
. . f f c f f f c f f f . . 
. . f c c f f f f c f f . . 
. . f c f f e e f f c f . . 
. . f f f 4 4 e e f f f . . 
. . f f d f 4 4 f d f f . . 
. . f 4 1 f 4 4 f 1 4 f . . 
. . . 4 4 4 4 4 4 4 4 . . . 
. . . . 4 4 4 4 4 4 . . . . 
. . e 4 b 2 2 2 2 b 4 e . . 
. . 4 d 2 2 2 2 2 2 d 4 . . 
. . 4 4 6 6 6 6 6 6 4 4 . . 
. . . . f f f f f f . . . . 
. . . . f f . . f f . . . . 
`, img`
. . . . . . . . . . . . . . 
. . . . . f f f f . . . . . 
. . . f f f f f c f f . . . 
. . f f c f f f c f f f . . 
. . f c c f f f f c f f . . 
. . f c f f e e f f c f . . 
. . f f f 4 4 e e f f f . . 
. . f f d f 4 4 f d f f . . 
. . f 4 1 f 4 4 f 1 4 f . . 
. . . 4 4 4 4 4 4 4 4 . . . 
. . . . 4 4 4 4 4 4 e f . . 
. . e 4 b 2 2 2 e d d 4 . . 
. . 4 d 2 2 2 2 e d d e . . 
. . 4 4 6 6 6 6 6 e e . . . 
. . . . f f f f f f . . . . 
. . . . . . . . f f . . . . 
`, img`
. . . . . . . . . . . . . . 
. . . . . f f f f . . . . . 
. . . f f f f f c f f . . . 
. . f f c f f f c f f f . . 
. . f c c f f f f c f f . . 
. . f c f f e e f f c f . . 
. . f f f 4 4 e e f f f . . 
. . f f d f 4 4 f d f f . . 
. . f 4 1 f 4 4 f 1 4 f . . 
. . . 4 4 4 4 4 4 4 4 . . . 
. . . . 4 4 4 4 4 4 . . . . 
. . e 4 b 2 2 2 2 b 4 e . . 
. . 4 d 2 2 2 2 2 2 d 4 . . 
. . 4 4 6 6 6 6 6 6 4 4 . . 
. . . . f f f f f f . . . . 
. . . . f f . . f f . . . . 
`];
            case "anim6":return [img`
. . . . . . . . . . . . . . . . 
. . 4 . . . 4 . . . . . . . . . 
. 4 f 4 d 4 f 4 . . . . . . . . 
. 4 f 4 4 4 f 4 . . . . . . . . 
. 4 4 d 4 d 4 4 . . . . . . . . 
. e 4 f 4 f 4 e . . . . e 4 f . 
. e 4 4 4 4 4 4 d . . . e 4 f . 
f d 4 4 4 4 4 d d e e e 4 4 4 . 
. . d d d 4 f d 4 4 4 4 4 4 . . 
. . . d d f f d d 4 4 4 4 4 4 . 
. . . . . d d d 4 4 f 4 f 4 4 . 
. . . . . . d 4 d 4 f f f d d . 
. . . . . . f . . . . . . . f . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . 4 . . . 4 . . . . . . . . . 
. 4 f 4 d 4 f 4 . . . . . . . . 
. 4 f 4 4 4 f 4 . . . . . . . . 
. 4 4 d 4 d 4 4 . . . . . . . . 
. e 4 f 4 f 4 e . . . . e 4 f . 
. e 4 4 4 4 4 4 d . . . e 4 f . 
f d 4 4 4 4 4 d d e e e 4 4 4 . 
. . d d d 4 f d 4 4 4 4 4 4 . . 
. . . d d f f d d 4 4 4 4 4 4 . 
. . . . . d d d 4 4 f 4 f 4 4 . 
. . . . . d d 4 d 4 f f f 4 d . 
. . . . f d 4 . . . . . . . d . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . 4 . . . 4 . . . . . . . . . 
. 4 f 4 d 4 f 4 . . . . . . . . 
. 4 f 4 4 4 f 4 . . . . . . . . 
. 4 4 d 4 d 4 4 . . . . . . . . 
. e 4 d 4 d 4 e . . . . e 4 f . 
. e 4 4 4 4 4 4 d . . . e 4 f . 
f d 4 4 4 4 4 d d e e e 4 4 4 . 
. . d d d 4 f d 4 4 4 4 4 4 . . 
. . . d d f f d d 4 4 4 4 4 4 . 
. . . . . d d d 4 4 f 4 f 4 4 . 
. . . . . . d 4 d 4 f f f d d . 
. . . . . . f . . . . . . . f . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . 4 . . . 4 . . . . . . . . . 
. 4 f 4 d 4 f 4 . . . . . . . . 
. 4 f 4 4 4 f 4 . . . . . . . . 
. 4 4 d 4 d 4 4 . . . . . . . . 
. e 4 f 4 f 4 e . . . . e 4 f . 
. e 4 4 4 4 4 4 d . . . e 4 f . 
f d 4 4 4 4 4 d d e e e 4 4 4 . 
. . d d d 4 f d 4 4 4 4 4 4 . . 
. . . d d f f d d 4 4 4 4 4 4 . 
. . . . . d d d 4 4 f 4 f 4 4 . 
. . . . . d d 4 d 4 f f f 4 d . 
. . . . f d 4 . . . . . . . d . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . 4 . . . 4 . . . . . . . . . 
. 4 f 4 d 4 f 4 . . . . . . . . 
. 4 f 4 4 4 f 4 . . . . . . . . 
. 4 4 d 4 d 4 4 . . . . . . . . 
. e 4 f 4 f 4 e . . . . e 4 f . 
. e 4 4 4 4 4 4 d . . . e 4 f . 
f d 4 4 4 4 4 d d e e e 4 4 4 . 
. . d d d 4 f d 4 4 4 4 4 4 . . 
. . . d d f f d d 4 4 4 4 4 4 . 
. . . . . d d d 4 4 f 4 f 4 4 . 
. . . . . . d 4 d 4 f f f d d . 
. . . . . . f . . . . . . . f . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . 4 . . . 4 . . . . . . . . . 
. 4 f 4 d 4 f 4 . . . . . . . . 
. 4 f 4 4 4 f 4 . . . . . . . . 
. 4 4 d 4 d 4 4 . . . . . . . . 
. e 4 f 4 f 4 e . . . . e 4 f . 
. e 4 4 4 4 4 4 d . . . e 4 f . 
f d 4 4 4 4 4 d d e e e 4 4 4 . 
. . d d d 4 f d 4 4 4 4 4 4 . . 
. . . d d f f d d 4 4 4 4 4 4 . 
. . . . . d d d 4 4 f 4 f 4 4 . 
. . . . . d d 4 d 4 f f f 4 d . 
. . . . f d 4 . . . . . . . d . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`];
            case "anim7":return [img`
......................aaaaaaaaaa..............................
......................aaaaaaaaaa..............................
....................aaaaaaaaaaaaaa............................
....................aaaaaaaaaaaaaa............................
....................aa77aaaaaa77aa............................
....................aa77aaaaaa77aa............................
....................aaaaffaaffaaaa............................
....................aaaaffaaffaaaa............................
..................aaaaaaff11ffaaaaaa..........................
..................aaaaaaff11ffaaaaaa..........................
..................aaaa11ffffff11aaaa..........................
..................aaaa11ffffff11aaaa..........................
..................aaaaaaffffffcaaaaa..........................
..................aaaaacffffffcaaaaa..........................
..............aaaaaaaaac11ff11caaaaaaaaa......................
..............aaaaaaaaac11ff11caaaaaaaaa......................
..........aaaaaaaaaaaaccccccccccaaaaaaaaaaaaaaaa..............
..........aaaaaaaaaaaaccccccccccaaaaaaaaaaaaaaaa..............
........aaaaaacccccccaaaaacccaaaaaccccccccccaaaaaa............
........aaaaaacccccccccaaaaaaaaaccccccccccccaaaaaa............
......aaaaccccccaaaaaaccccccccccccaaaaaaaaaacccaaaaa..........
......aaaaccccccaaaaaaccccccccccccaaaaaaaaaacccaaaaa..........
......aaaaaaaaaaaaaaaaaaaaaccaaaaaaaaaccaaaaaaaaaaaaaa........
......aaaaaaaaaaaaaaaaaaaaaccaaaaaaaaaccaaaaaaaaaaaaaa........
......aaaaaaaaaaaaaaaaaaaaaccaaaaaaaaaaaaaaaaaaaaaaaaaaa......
......aaaaaaaaaccaaaaaaaaaaccaaaaaaaaaaaaaaaaaaaaaaaaaaa......
......aaaaaaaaaccaaaaaaaaaaccaaaaaaaaaaaaaaaaaaaaaaaaaaa......
......aaaaaaaaaaaaaaaaaccaaccaaaaccaaaaaaccccaaaaaaaaaaa......
....aaaaaaaa..aaaaaaaaaccaaccaaaaccaaaaaaccccaaaaaaaaaaa......
....aaaaaaaa..aaaccccaaaaaaccaaaaaaaaaaccccaaaaaaaaaaaaaaa....
....aaaaaaaa....accccaaaaaaccaaaaaaaaaaccccaaaa..aaaaaaaaa....
....aaaaaaaa....aaaacccccccccccccccccccccaaaaaa..aaaaaaaaa....
....aaaaaaaa....aaaacccccccccccccccccccccaaaa....aaaaaaaaa....
....aaaaaaaa....aaaaaaaaccaaaaaaaaaaaccaaaaaa....aaaaaaaaa....
..aaaaaaaaaaaa....aaaaaaccaaaaaaaaaaaccaaaa......aaaaaaaaaaa..
..aaaaaaaaaaaa....aaccccccaaaaaaaaaaaccaaaa....aaaaaaaaaaaaa..
..aaaaaaaaaaaa....aaccccccaaaaaaaaaaaccaaaa....aaaaaaaaaaaaa..
..aaaaaaaaaaaa....aaccaaaaaaaaaaaaaaaccaaaa....aaaaaaaaaaaaa..
aaaaaaaaaaaaaa..aaaaccaaaaaddaaaaaaaaccaaaaaa..aaaaaaaaaaaaaaa
aaaaaaaaaaaaaa..aaaaccaaaaaddaaaaaaaaccaaaaaa..aaaaaaaaaaaaaaa
aaaaaaaaaaaaaa..aaaaccaaaaaddaaddaaaaaaaaaaaa..aaaaaaaaaaaaaaa
aaaaaaaaaaaaaa..aaaaccaaaaaddaaddaaaaaaaaaaaa..aaaaaaaaaaaaaaa
aaaaaaaaaaaa....aaaaaaaaaddddddddddddaaaaaaaa..aaaaaaaaaaaaaaa
aaaaaaaaaaaa....aaaaaaaaaddddddddddddaaaaaaaa....aaaaaaaaaaaaa
..aaaaaaaaaa....aaaaaaaaa..ddddddddddaaaaaaaa....aaaaaaaaaaa..
..aaaaaaaaaa....aaaaaaaaa..ddddddddddaaaaaaaa....aaaaaaaaaaa..
..aaaaaaaaaa....aaaaaaaaa..dddddd....aaaaaaaa....aaaaaaaaaaa..
..aaaaaaaaaa....aaaaaaaaa..dddddd....aaaaaaaaaa..aaaaaaaaaaa..
....aaaaaaaa..aaaaaaaaa....dddddd......aaaaaaaa..aaaaaaaaa....
....aaaaaaaa..aaaaaaaaa....dddddd......aaaaaaaa..aaaaaaaaa....
....ccaaaa....aaaaaaaaa...ddddd........aaaaaaaa....aaaaaaa....
....ccaaaa....aaaaaaaaa...ddddd........aaaaaaaa....aaaaaaa....
..............aaaaaaaaa...ddddd........aaaaaaaa...............
..............aaaaaaaaa...ddddd........aaaaaaaa...............
....c.....aaaaaaaaaaaaa...ddddddddddd..aaaaaaaaaaa......c.....
....c.....aaaaaaaaaaaaa.....ddddddddd..aaaaaaaaaaa......cc....
...ccc..aaaaaaaaaaaaaaa.....ddddd33dd..aaaaaaaaaaaaa.....c....
....c...aaaaaaaaaaaaaaa.......ddd33dd..aaaaaaaaaaaaa.....c....
........aaaaaaaaaaaaaaa.......ddddd33..aaaaaaaaaaaaa..........
........aaaaaaaaaaaaaaa.......ddddd33..aaaaaaaaaaaaa..........
`, img`
......................aaaaaaaaaa..............................
......................aaaaaaaaaa..............................
....................aaaaaaaaaaaaaa............................
....................aaaaaaaaaaaaaa............................
....................aa77aaaaaa77aa............................
....................aa77aaaaaa77aa............................
....................aaaaffaaffaaaa............................
....................aaaaffaaffaaaa............................
..................aaaaaaff11ffaaaaaa..........................
..................aaaaaaff11ffaaaaaa..........................
..................aaaa11ffffff11aaaa..........................
..................aaaa11ffffff11aaaa..........................
..................aaaaaaffffffcaaaaa..........................
..................aaaaacffffffcaaaaa..........................
..............aaaaaaaaac11ff11caaaaaaaaa......................
..............aaaaaaaaac11ff11caaaaaaaaa......................
..........aaaaaaaaaaaaccccccccccaaaaaaaaaaaaaaaa..............
..........aaaaaaaaaaaaccccccccccaaaaaaaaaaaaaaaa..............
........aaaaaacccccccaaaaacccaaaaaccccccccccaaaaaa............
........aaaaaacccccccccaaaaaaaaaccccccccccccaaaaaa............
......aaaaccccccaaaaaaccccccccccccaaaaaaaaaacccaaaaa..........
......aaaaccccccaaaaaaccccccccccccaaaaaaaaaacccaaaaa..........
......aaaaaaaaaaaaaaaaaaaaaccaaaaaaaaaccaaaaaaaaaaaaaa........
......aaaaaaaaaaaaaaaaaaaaaccaaaaaaaaaccaaaaaaaaaaaaaa........
......aaaaaaaaaaaaaaaaaaaaaccaaaaaaaaaaaaaaaaaaaaaaaaaaa......
......aaaaaaaaaccaaaaaaaaaaccaaaaaaaaaaaaaaaaaaaaaaaaaaa......
......aaaaaaaaaccaaaaaaaaaaccaaaaaaaaaaaaaaaaaaaaaaaaaaa......
......aaaaaaaaaaaaaaaaaccaaccaaaaccaaaaaaccccaaaaaaaaaaa......
....aaaaaaaa..aaaaaaaaaccaaccaaaaccaaaaaaccccaaaaaaaaaaa......
....aaaaaaaa..aaaccccaaaaaaccaaaaaaaaaaccccaaaaaaaaaaaaaaa....
....aaaaaaaa....accccaaaaaaccaaaaaaaaaaccccaaaa..aaaaaaaaa....
....aaaaaaaa....aaaacccccccccccccccccccccaaaaaa..aaaaaaaaa....
....aaaaaaaa....aaaacccccccccccccccccccccaaaa....aaaaaaaaa....
....aaaaaaaa....aaaaaaaaccaaaaaaaaaaaccaaaaaa....aaaaaaaaa....
..aaaaaaaaaaaa....aaaaaaccaaaaaaaaaaaccaaaa......aaaaaaaaaaa..
..aaaaaaaaaaaa....aaccccccaaaaaaaaaaaccaaaa....aaaaaaaaaaaaa..
..aaaaaaaaaaaa....aaccccccaaaaaaaaaaaccaaaa....aaaaaaaaaaaaa..
..aaaaaaaaaaaa....aaccaaaaaaaaaaaaaaaccaaaa....aaaaaaaaaaaaa..
aaaaaaaaaaaaaa..aaaaccaaaaaddaaaaaaaaccaaaaaa..aaaaaaaaaaaaaaa
aaaaaaaaaaaaaa..aaaaccaaaaaddaaaaaaaaccaaaaaa..aaaaaaaaaaaaaaa
aaaaaaaaaaaaaa..aaaaccaaaaaddaaddaaaaaaaaaaaa..aaaaaaaaaaaaaaa
aaaaaaaaaaaaaa..aaaaccaaaaaddaaddaaaaaaaaaaaa..aaaaaaaaaaaaaaa
aaaaaaaaaaaa....aaaaaaaaaddddddddddddaaaaaaaa..aaaaaaaaaaaaaaa
aaaaaaaaaaaa....aaaaaaaaaddddddddddddaaaaaaaa....aaaaaaaaaaaaa
..aaaaaaaaaa....aaaaaaaaa..ddddddddddaaaaaaaa....aaaaaaaaaaa..
..aaaaaaaaaa....aaaaaaaaa..ddddddddddaaaaaaaa....aaaaaaaaaaa..
..aaaaaaaaaa....aaaaaaaaa..dddddd....aaaaaaaa....aaaaaaaaaaa..
..aaaaaaaaaa....aaaaaaaaa..dddddd....aaaaaaaaaa..aaaaaaaaaaa..
....aaaaaaaa..aaaaaaaaa....dddddd......aaaaaaaa..aaaaaaaaa....
....aaaaaaaa..aaaaaaaaa....dddddd......aaaaaaaa..aaaaaaaaa....
...cccaaaa....aaaaaaaaa...ddddd........aaaaaaaa....aaaaacc....
....ccaaaa....aaaaaaaaa...ddddd........aaaaaaaa....aaaaacc....
....c.........aaaaaaaaa...ddddd........aaaaaaaa..........c....
..............aaaaaaaaa...ddddd........aaaaaaaa...............
..........aaaaaaaaaaaaa...ddddddddddd..aaaaaaaaaaa............
....c.....aaaaaaaaaaaaa.....ddddddddd..aaaaaaaaaaa......c.....
....c...aaaaaaaaaaaaaaa.....ddddd33dd..aaaaaaaaaaaaa....cc....
...ccc..aaaaaaaaaaaaaaa.......ddd33dd..aaaaaaaaaaaaa.....c....
....c...aaaaaaaaaaaaaaa.......ddddd33..aaaaaaaaaaaaa.....c....
........aaaaaaaaaaaaaaa.......ddddd33..aaaaaaaaaaaaa..........
`, img`
......................aaaaaaaaaa..............................
......................aaaaaaaaaa..............................
....................aaaaaaaaaaaaaa............................
....................aaaaaaaaaaaaaa............................
....................aa77aaaaaa77aa............................
....................aa77aaaaaa77aa............................
....................aaaaffaaffaaaa............................
....................aaaaffaaffaaaa............................
..................aaaaaaff11ffaaaaaa..........................
..................aaaaaaff11ffaaaaaa..........................
..................aaaa11ffffff11aaaa..........................
..................aaaa11ffffff11aaaa..........................
..................aaaaaaffffffcaaaaa..........................
..................aaaaacffffffcaaaaa..........................
..............aaaaaaaaac11ff11caaaaaaaaa......................
..............aaaaaaaaac11ff11caaaaaaaaa......................
..........aaaaaaaaaaaaccccccccccaaaaaaaaaaaaaaaa..............
..........aaaaaaaaaaaaccccccccccaaaaaaaaaaaaaaaa..............
........aaaaaacccccccaaaaacccaaaaaccccccccccaaaaaa............
........aaaaaacccccccccaaaaaaaaaccccccccccccaaaaaa............
......aaaaccccccaaaaaaccccccccccccaaaaaaaaaacccaaaaa..........
......aaaaccccccaaaaaaccccccccccccaaaaaaaaaacccaaaaa..........
......aaaaaaaaaaaaaaaaaaaaaccaaaaaaaaaccaaaaaaaaaaaaaa........
......aaaaaaaaaaaaaaaaaaaaaccaaaaaaaaaccaaaaaaaaaaaaaa........
......aaaaaaaaaaaaaaaaaaaaaccaaaaaaaaaaaaaaaaaaaaaaaaaaa......
......aaaaaaaaaccaaaaaaaaaaccaaaaaaaaaaaaaaaaaaaaaaaaaaa......
......aaaaaaaaaccaaaaaaaaaaccaaaaaaaaaaaaaaaaaaaaaaaaaaa......
......aaaaaaaaaaaaaaaaaccaaccaaaaccaaaaaaccccaaaaaaaaaaa......
....aaaaaaaa..aaaaaaaaaccaaccaaaaccaaaaaaccccaaaaaaaaaaa......
....aaaaaaaa..aaaccccaaaaaaccaaaaaaaaaaccccaaaaaaaaaaaaaaa....
....aaaaaaaa....accccaaaaaaccaaaaaaaaaaccccaaaa..aaaaaaaaa....
....aaaaaaaa....aaaacccccccccccccccccccccaaaaaa..aaaaaaaaa....
....aaaaaaaa....aaaacccccccccccccccccccccaaaa....aaaaaaaaa....
....aaaaaaaa....aaaaaaaaccaaaaaaaaaaaccaaaaaa....aaaaaaaaa....
..aaaaaaaaaaaa....aaaaaaccaaaaaaaaaaaccaaaa......aaaaaaaaaaa..
..aaaaaaaaaaaa....aaccccccaaaaaaaaaaaccaaaa....aaaaaaaaaaaaa..
..aaaaaaaaaaaa....aaccccccaaaaaaaaaaaccaaaa....aaaaaaaaaaaaa..
..aaaaaaaaaaaa....aaccaaaaaaaaaaaaaaaccaaaa....aaaaaaaaaaaaa..
aaaaaaaaaaaaaa..aaaaccaaaaaddaaaaaaaaccaaaaaa..aaaaaaaaaaaaaaa
aaaaaaaaaaaaaa..aaaaccaaaaaddaaaaaaaaccaaaaaa..aaaaaaaaaaaaaaa
aaaaaaaaaaaaaa..aaaaccaaaaaddaaddaaaaaaaaaaaa..aaaaaaaaaaaaaaa
aaaaaaaaaaaaaa..aaaaccaaaaaddaaddaaaaaaaaaaaa..aaaaaaaaaaaaaaa
aaaaaaaaaaaa....aaaaaaaaaddddddddddddaaaaaaaa..aaaaaaaaaaaaaaa
aaaaaaaaaaaa....aaaaaaaaaddddddddddddaaaaaaaa....aaaaaaaaaaaaa
..aaaaaaaaaa....aaaaaaaaa..ddddddddddaaaaaaaa....aaaaaaaaaaa..
..aaaaaaaaaa....aaaaaaaaa..ddddddddddaaaaaaaa....aaaaaaaaaaa..
..aaaaaaaaaa....aaaaaaaaa..dddddd....aaaaaaaa....aaaaaaaaaaa..
..aaaaaaaaaa....aaaaaaaaa..dddddd....aaaaaaaaaa..aaaaaaaaaaa..
....aaaaaaaa..aaaaaaaaa....dddddd......aaaaaaaa..aaaaaaaaa....
....aaaaaaaa..aaaaaaaaa....dddddd......aaaaaaaa..aaaaaaaaa....
....ccaaaa....aaaaaaaaa...ddddd........aaaaaaaa....aaaaacc....
...cccaaaa....aaaaaaaaa...ddddd........aaaaaaaa....aaaaacc....
....cc........aaaaaaaaa...ddddd........aaaaaaaa..........c....
....c.........aaaaaaaaa...ddddd........aaaaaaaa..........c....
..........aaaaaaaaaaaaa...ddddddddddd..aaaaaaaaaaa............
..........aaaaaaaaaaaaa.....ddddddddd..aaaaaaaaaaa............
....c...aaaaaaaaaaaaaaa.....ddddd33dd..aaaaaaaaaaaaa....c.....
....c...aaaaaaaaaaaaaaa.......ddd33dd..aaaaaaaaaaaaa....cc....
...ccc..aaaaaaaaaaaaaaa.......ddddd33..aaaaaaaaaaaaa.....c....
....c...aaaaaaaaaaaaaaa.......ddddd33..aaaaaaaaaaaaa.....c....
`, img`
......................aaaaaaaaaa..............................
......................aaaaaaaaaa..............................
....................aaaaaaaaaaaaaa............................
....................aaaaaaaaaaaaaa............................
....................aa77aaaaaa77aa............................
....................aa77aaaaaa77aa............................
....................aaaaffaaffaaaa............................
....................aaaaffaaffaaaa............................
..................aaaaaaff11ffaaaaaa..........................
..................aaaaaaff11ffaaaaaa..........................
..................aaaa11ffffff11aaaa..........................
..................aaaa11ffffff11aaaa..........................
..................aaaaaaffffffcaaaaa..........................
..................aaaaacffffffcaaaaa..........................
..............aaaaaaaaac11ff11caaaaaaaaa......................
..............aaaaaaaaac11ff11caaaaaaaaa......................
..........aaaaaaaaaaaaccccccccccaaaaaaaaaaaaaaaa..............
..........aaaaaaaaaaaaccccccccccaaaaaaaaaaaaaaaa..............
........aaaaaacccccccaaaaacccaaaaaccccccccccaaaaaa............
........aaaaaacccccccccaaaaaaaaaccccccccccccaaaaaa............
......aaaaccccccaaaaaaccccccccccccaaaaaaaaaacccaaaaa..........
......aaaaccccccaaaaaaccccccccccccaaaaaaaaaacccaaaaa..........
......aaaaaaaaaaaaaaaaaaaaaccaaaaaaaaaccaaaaaaaaaaaaaa........
......aaaaaaaaaaaaaaaaaaaaaccaaaaaaaaaccaaaaaaaaaaaaaa........
......aaaaaaaaaaaaaaaaaaaaaccaaaaaaaaaaaaaaaaaaaaaaaaaaa......
......aaaaaaaaaccaaaaaaaaaaccaaaaaaaaaaaaaaaaaaaaaaaaaaa......
......aaaaaaaaaccaaaaaaaaaaccaaaaaaaaaaaaaaaaaaaaaaaaaaa......
......aaaaaaaaaaaaaaaaaccaaccaaaaccaaaaaaccccaaaaaaaaaaa......
....aaaaaaaa..aaaaaaaaaccaaccaaaaccaaaaaaccccaaaaaaaaaaa......
....aaaaaaaa..aaaccccaaaaaaccaaaaaaaaaaccccaaaaaaaaaaaaaaa....
....aaaaaaaa....accccaaaaaaccaaaaaaaaaaccccaaaa..aaaaaaaaa....
....aaaaaaaa....aaaacccccccccccccccccccccaaaaaa..aaaaaaaaa....
....aaaaaaaa....aaaacccccccccccccccccccccaaaa....aaaaaaaaa....
....aaaaaaaa....aaaaaaaaccaaaaaaaaaaaccaaaaaa....aaaaaaaaa....
..aaaaaaaaaaaa....aaaaaaccaaaaaaaaaaaccaaaa......aaaaaaaaaaa..
..aaaaaaaaaaaa....aaccccccaaaaaaaaaaaccaaaa....aaaaaaaaaaaaa..
..aaaaaaaaaaaa....aaccccccaaaaaaaaaaaccaaaa....aaaaaaaaaaaaa..
..aaaaaaaaaaaa....aaccaaaaaaaaaaaaaaaccaaaa....aaaaaaaaaaaaa..
aaaaaaaaaaaaaa..aaaaccaaaaaddaaaaaaaaccaaaaaa..aaaaaaaaaaaaaaa
aaaaaaaaaaaaaa..aaaaccaaaaaddaaaaaaaaccaaaaaa..aaaaaaaaaaaaaaa
aaaaaaaaaaaaaa..aaaaccaaaaaddaaddaaaaaaaaaaaa..aaaaaaaaaaaaaaa
aaaaaaaaaaaaaa..aaaaccaaaaaddaaddaaaaaaaaaaaa..aaaaaaaaaaaaaaa
aaaaaaaaaaaa....aaaaaaaaaddddddddddddaaaaaaaa..aaaaaaaaaaaaaaa
aaaaaaaaaaaa....aaaaaaaaaddddddddddddaaaaaaaa....aaaaaaaaaaaaa
..aaaaaaaaaa....aaaaaaaaa..ddddddddddaaaaaaaa....aaaaaaaaaaa..
..aaaaaaaaaa....aaaaaaaaa..ddddddddddaaaaaaaa....aaaaaaaaaaa..
..aaaaaaaaaa....aaaaaaaaa..dddddd....aaaaaaaa....aaaaaaaaaaa..
..aaaaaaaaaa....aaaaaaaaa..dddddd....aaaaaaaaaa..aaaaaaaaaaa..
....aaaaaaaa..aaaaaaaaa....dddddd......aaaaaaaa..aaaaaaaaa....
....aaaaaaaa..aaaaaaaaa....dddddd......aaaaaaaa..aaaaaaaaa....
....ccaaaa....aaaaaaaaa...ddddd........aaaaaaaa....aaaaacc....
....ccaaaa....aaaaaaaaa...ddddd........aaaaaaaa....aaaaacc....
...cc.........aaaaaaaaa...ddddd........aaaaaaaa..........c....
....cc........aaaaaaaaa...ddddd........aaaaaaaa..........c....
....c.....aaaaaaaaaaaaa...ddddddddddd..aaaaaaaaaaa.......c....
..........aaaaaaaaaaaaa.....ddddddddd..aaaaaaaaaaa............
........aaaaaaaaaaaaaaa.....ddddd33dd..aaaaaaaaaaaaa..........
c...c...aaaaaaaaaaaaaaa.......ddd33dd..aaaaaaaaaaaaa.c..c...c.
.c..c..ccaaaaaaaaaaaaaa.......ddddd33..aaaaaaaaaaaaa..c.cc.c..
...ccc..ccaaaaaaaaaaaaa.......ddddd33..aaaaaaaaaaaaa.....c....
`, img`
......................aaaaaaaaaa..............................
......................aaaaaaaaaa..............................
....................aaaaaaaaaaaaaa............................
....................aaaaaaaaaaaaaa............................
....................aa77aaaaaa77aa............................
....................aa77aaaaaa77aa............................
....................aaaaffaaffaaaa............................
....................aaaaffaaffaaaa............................
..................aaaaaaff11ffaaaaaa..........................
..................aaaaaaff11ffaaaaaa..........................
..................aaaa11ffffff11aaaa..........................
..................aaaa11ffffff11aaaa..........................
..................aaaaaaffffffcaaaaa..........................
..................aaaaacffffffcaaaaa..........................
..............aaaaaaaaac11ff11caaaaaaaaa......................
..............aaaaaaaaac11ff11caaaaaaaaa......................
..........aaaaaaaaaaaaccccccccccaaaaaaaaaaaaaaaa..............
..........aaaaaaaaaaaaccccccccccaaaaaaaaaaaaaaaa..............
........aaaaaacccccccaaaaacccaaaaaccccccccccaaaaaa............
........aaaaaacccccccccaaaaaaaaaccccccccccccaaaaaa............
......aaaaccccccaaaaaaccccccccccccaaaaaaaaaacccaaaaa..........
......aaaaccccccaaaaaaccccccccccccaaaaaaaaaacccaaaaa..........
......aaaaaaaaaaaaaaaaaaaaaccaaaaaaaaaccaaaaaaaaaaaaaa........
......aaaaaaaaaaaaaaaaaaaaaccaaaaaaaaaccaaaaaaaaaaaaaa........
......aaaaaaaaaaaaaaaaaaaaaccaaaaaaaaaaaaaaaaaaaaaaaaaaa......
......aaaaaaaaaccaaaaaaaaaaccaaaaaaaaaaaaaaaaaaaaaaaaaaa......
......aaaaaaaaaccaaaaaaaaaaccaaaaaaaaaaaaaaaaaaaaaaaaaaa......
......aaaaaaaaaaaaaaaaaccaaccaaaaccaaaaaaccccaaaaaaaaaaa......
....aaaaaaaa..aaaaaaaaaccaaccaaaaccaaaaaaccccaaaaaaaaaaa......
....aaaaaaaa..aaaccccaaaaaaccaaaaaaaaaaccccaaaaaaaaaaaaaaa....
....aaaaaaaa....accccaaaaaaccaaaaaaaaaaccccaaaa..aaaaaaaaa....
....aaaaaaaa....aaaacccccccccccccccccccccaaaaaa..aaaaaaaaa....
....aaaaaaaa....aaaacccccccccccccccccccccaaaa....aaaaaaaaa....
....aaaaaaaa....aaaaaaaaccaaaaaaaaaaaccaaaaaa....aaaaaaaaa....
..aaaaaaaaaaaa....aaaaaaccaaaaaaaaaaaccaaaa......aaaaaaaaaaa..
..aaaaaaaaaaaa....aaccccccaaaaaaaaaaaccaaaa....aaaaaaaaaaaaa..
..aaaaaaaaaaaa....aaccccccaaaaaaaaaaaccaaaa....aaaaaaaaaaaaa..
..aaaaaaaaaaaa....aaccaaaaaaaaaaaaaaaccaaaa....aaaaaaaaaaaaa..
aaaaaaaaaaaaaa..aaaaccaaaaaddaaaaaaaaccaaaaaa..aaaaaaaaaaaaaaa
aaaaaaaaaaaaaa..aaaaccaaaaaddaaaaaaaaccaaaaaa..aaaaaaaaaaaaaaa
aaaaaaaaaaaaaa..aaaaccaaaaaddaaddaaaaaaaaaaaa..aaaaaaaaaaaaaaa
aaaaaaaaaaaaaa..aaaaccaaaaaddaaddaaaaaaaaaaaa..aaaaaaaaaaaaaaa
aaaaaaaaaaaa....aaaaaaaaaddddddddddddaaaaaaaa..aaaaaaaaaaaaaaa
aaaaaaaaaaaa....aaaaaaaaaddddddddddddaaaaaaaa....aaaaaaaaaaaaa
..aaaaaaaaaa....aaaaaaaaa..ddddddddddaaaaaaaa....aaaaaaaaaaa..
..aaaaaaaaaa....aaaaaaaaa..ddddddddddaaaaaaaa....aaaaaaaaaaa..
..aaaaaaaaaa....aaaaaaaaa..dddddd....aaaaaaaa....aaaaaaaaaaa..
..aaaaaaaaaa....aaaaaaaaa..dddddd....aaaaaaaaaa..aaaaaaaaaaa..
....aaaaaaaa..aaaaaaaaa....dddddd......aaaaaaaa..aaaaaaaaa....
....aaaaaaaa..aaaaaaaaa....dddddd......aaaaaaaa..aaaaaaaaa....
....ccaaaa....aaaaaaaaa...ddddd........aaaaaaaa....aaaaacc....
....ccaaaa....aaaaaaaaa...ddddd........aaaaaaaa....aaaaacc....
....c.........aaaaaaaaa...ddddd........aaaaaaaa.........c.....
...cc.........aaaaaaaaa...ddddd........aaaaaaaa.........cc....
....cc....aaaaaaaaaaaaa...ddddddddddd..aaaaaaaaaaa.......c....
....c.....aaaaaaaaaaaaa.....ddddddddd..aaaaaaaaaaa.......c....
........aaaaaaaaaaaaaaa.....ddddd33dd..aaaaaaaaaaaaa..........
........aaaaaaaaaaaaaaa.......ddd33dd..aaaaaaaaaaaaa..........
.c..c...aaacaaaaaaaaaaa.......ddddd33..aaaaaaaaaaaaa.c..c...c.
..c.c...cccaaaaaaaaaaaa.......ddddd33..aaaaaaaaaaaaa..c.cc.c..
`];
            case "anim16":return [img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`];
            case "anim17":return [img`
. . . . . . . . . . . . . . 
. . . . . f f f f . . . . . 
. . . f f c f f f f f . . . 
. . f f f c f f f c f f . . 
. . f f c f f f f c c f . . 
. . f c f f f f f f c f . . 
. . f f f f f f f f f f . . 
. . f f f f f f f f f f . . 
. . f f f f f f f f f f . . 
. . . 4 f f f f f f 4 . . . 
. . . . 4 4 4 4 4 4 . . . . 
. . e 4 2 2 2 2 2 2 4 e . . 
. . 4 4 2 2 2 2 2 2 d 4 . . 
. . . . 6 6 6 6 6 6 4 4 . . 
. . . . f f f f f f . . . . 
. . . . f f . . . . . . . . 
`, img`
. . . . . . . . . . . . . . 
. . . . . f f f f . . . . . 
. . . f f c f f f f f . . . 
. . f f f c f f f c f f . . 
. . f f c f f f f c c f . . 
. . f c f f f f f f c f . . 
. . f f f f f f f f f f . . 
. . f f f f f f f f f f . . 
. . f f f f f f f f f f . . 
. . . 4 f f f f f f 4 . . . 
. . . . 4 4 4 4 4 4 . . . . 
. . e 4 2 2 2 2 2 2 4 e . . 
. . 4 d 2 2 2 2 2 2 d 4 . . 
. . 4 4 6 6 6 6 6 6 4 4 . . 
. . . . f f f f f f . . . . 
. . . . f f . . f f . . . . 
`, img`
. . . . . . . . . . . . . . 
. . . . . f f f f . . . . . 
. . . f f c f f f f f . . . 
. . f f f c f f f c f f . . 
. . f f c f f f f c c f . . 
. . f c f f f f f f c f . . 
. . f f f f f f f f f f . . 
. . f f f f f f f f f f . . 
. . f f f f f f f f f f . . 
. . . 4 f f f f f f 4 . . . 
. . . . 4 4 4 4 4 4 . . . . 
. . e 4 2 2 2 2 2 2 4 e . . 
. . 4 d 2 2 2 2 2 2 4 4 . . 
. . 4 4 6 6 6 6 6 6 . . . . 
. . . . f f f f f f . . . . 
. . . . . . . . f f . . . . 
`, img`
. . . . . . . . . . . . . . 
. . . . . f f f f . . . . . 
. . . f f c f f f f f . . . 
. . f f f c f f f c f f . . 
. . f f c f f f f c c f . . 
. . f c f f f f f f c f . . 
. . f f f f f f f f f f . . 
. . f f f f f f f f f f . . 
. . f f f f f f f f f f . . 
. . . 4 f f f f f f 4 . . . 
. . . . 4 4 4 4 4 4 . . . . 
. . e 4 2 2 2 2 2 2 4 e . . 
. . 4 d 2 2 2 2 2 2 d 4 . . 
. . 4 4 6 6 6 6 6 6 4 4 . . 
. . . . f f f f f f . . . . 
. . . . f f . . f f . . . . 
`];
            case "anim18":return [img`
. . . . . f f f f f . . . . 
. . . f f f f f f f f f . . 
. . f f f c f f f f f f . . 
. . f f c f f f c f f f f . 
. f c c f f f c c f f c f . 
. f f f f 4 f f f f c c f . 
. . f f 4 4 f f f f f f f . 
. . . . 4 4 f b f f f f f . 
. . . . 4 4 f 1 4 f f f . . 
. . . . 4 4 4 4 4 f f f . . 
. . . . . 4 4 4 4 e . . . . 
. . . . . 2 2 2 4 4 . . . . 
. . . . . 2 2 2 4 4 . . . . 
. . . . . 6 6 6 6 6 . . . . 
. . . . f f f f f f . . . . 
. . . . f f . . f f . . . . 
`, img`
. . . . . f f f f f . . . . 
. . . f f f f f f f f f . . 
. . f f f c f f f f f f . . 
. . f f c f f f c f f f f . 
. f c c f f f c c f f c f . 
. f f f f 4 f f f f c c f . 
. . f f 4 4 f f f f f f f . 
. . . . 4 4 f b f f f f f . 
. . . . 4 4 f 1 4 f f f . . 
. . . . 4 4 4 4 4 f f f . . 
. . . . . 4 4 4 4 e . . . . 
. . . . . 2 2 2 4 4 . . . . 
. . . . . 2 2 2 4 4 . . . . 
. . . . . 6 6 6 6 6 . . . . 
. . . . . f f f f f . . . . 
. . . . . . f f f . . . . . 
`, img`
. . . . . f f f f f . . . . 
. . . f f f f f f f f f . . 
. . f f f c f f f f f f . . 
. . f f c f f f c f f f f . 
. f c c f f f c c f f c f . 
. f f f f 4 f f f f c c f . 
. . f f 4 4 f f f f f f f . 
. . . . 4 4 f b f f f f f . 
. . . . 4 4 f 1 4 f f f . . 
. . . . 4 4 4 4 4 f f f . . 
. . . . . 4 4 4 4 e . . . . 
. . . . . 2 2 2 4 4 . . . . 
. . . . . 2 2 2 4 4 . . . . 
. . . . . 6 6 6 6 6 . . . . 
. . . . . f f f f f . . . . 
. . . . . f f . f f . . . . 
`, img`
. . . . . f f f f f . . . . 
. . . f f f f f f f f f . . 
. . f f f c f f f f f f . . 
. . f f c f f f c f f f f . 
. f c c f f f c c f f c f . 
. f f f f 4 f f f f c c f . 
. . f f 4 4 f f f f f f f . 
. . . . 4 4 f b f f f f f . 
. . . . 4 4 f 1 4 f f f . . 
. . . . 4 4 4 4 4 f f f . . 
. . . . . 4 4 4 4 e . . . . 
. . . . . 2 2 2 4 4 . . . . 
. . . . . 2 2 2 4 4 . . . . 
. . . . . 6 6 6 6 6 . . . . 
. . . . . f f f f f . . . . 
. . . . . . f f f . . . . . 
`];
            case "anim19":return [img`
. . . . f f f f f . . . . . 
. . f f f f f f f f f . . . 
. . f f f f f f c f f f . . 
. f f f f c f f f c f f . . 
. f c f f c c f f f c c f . 
. f c c f f f f e f f f f . 
. f f f f f f f 4 4 f f f . 
. f f f f f b f 4 4 f f . . 
. . f f f 4 1 f 4 4 . . . . 
. . f f f 4 4 4 4 4 . . . . 
. . . . e 4 4 4 4 . . . . . 
. . . . 4 4 2 2 2 . . . . . 
. . . . 4 4 2 2 2 . . . . . 
. . . . 6 6 6 6 6 . . . . . 
. . . . f f f f f f . . . . 
. . . . f f . . f f . . . . 
`, img`
. . . . f f f f f . . . . . 
. . f f f f f f f f f . . . 
. . f f f f f f c f f f . . 
. f f f f c f f f c f f . . 
. f c f f c c f f f c c f . 
. f c c f f f f e f f f f . 
. f f f f f f f 4 4 f f f . 
. f f f f f b f 4 4 f f . . 
. . f f f 4 1 f 4 4 . . . . 
. . f f f 4 4 4 4 4 . . . . 
. . . . e 4 4 4 4 . . . . . 
. . . . 4 4 2 2 2 . . . . . 
. . . . 4 4 2 2 2 . . . . . 
. . . . 6 6 6 6 6 . . . . . 
. . . . f f f f f . . . . . 
. . . . . f f f . . . . . . 
`, img`
. . . . f f f f f . . . . . 
. . f f f f f f f f f . . . 
. . f f f f f f c f f f . . 
. f f f f c f f f c f f . . 
. f c f f c c f f f c c f . 
. f c c f f f f e f f f f . 
. f f f f f f f 4 4 f f f . 
. f f f f f b f 4 4 f f . . 
. . f f f 4 1 f 4 4 . . . . 
. . f f f 4 4 4 4 4 . . . . 
. . . . e 4 4 4 4 . . . . . 
. . . . 4 4 2 2 2 . . . . . 
. . . . 4 4 2 2 2 . . . . . 
. . . . 6 6 6 6 6 . . . . . 
. . . . f f f f f . . . . . 
. . . . f f . f f . . . . . 
`, img`
. . . . f f f f f . . . . . 
. . f f f f f f f f f . . . 
. . f f f f f f c f f f . . 
. f f f f c f f f c f f . . 
. f c f f c c f f f c c f . 
. f c c f f f f e f f f f . 
. f f f f f f f 4 4 f f f . 
. f f f f f b f 4 4 f f . . 
. . f f f 4 1 f 4 4 . . . . 
. . f f f 4 4 4 4 4 . . . . 
. . . . e 4 4 4 4 . . . . . 
. . . . 4 4 2 2 2 . . . . . 
. . . . 4 4 2 2 2 . . . . . 
. . . . 6 6 6 6 6 . . . . . 
. . . . f f f f f . . . . . 
. . . . . f f f . . . . . . 
`];
            case "anim20":return [img`
. . . . . . . . . . . . . . 
. . . . . f f f f . . . . . 
. . . f f f f f c f f . . . 
. . f f c f f f c f f f . . 
. . f c c f f f f c f f . . 
. . f c f f e e f f c f . . 
. . f f f 4 4 e e f f f . . 
. . f f d f 4 4 f d f f . . 
. . f 4 1 f 4 4 f 1 4 f . . 
. . . 4 4 4 4 4 4 4 4 . . . 
. . f e 4 4 4 4 4 4 . . . . 
. . 4 d d e 2 2 2 b 4 e . . 
. . e d d e 2 2 2 2 d 4 . . 
. . . e e f 6 6 6 6 4 4 . . 
. . . . f f f f f f . . . . 
. . . . f f . . . . . . . . 
`, img`
. . . . . . . . . . . . . . 
. . . . . f f f f . . . . . 
. . . f f f f f c f f . . . 
. . f f c f f f c f f f . . 
. . f c c f f f f c f f . . 
. . f c f f e e f f c f . . 
. . f f f 4 4 e e f f f . . 
. . f f d f 4 4 f d f f . . 
. . f 4 1 f 4 4 f 1 4 f . . 
. . . 4 4 4 4 4 4 4 4 . . . 
. . . . 4 4 4 4 4 4 . . . . 
. . e 4 b 2 2 2 2 b 4 e . . 
. . 4 d 2 2 2 2 2 2 d 4 . . 
. . 4 4 6 6 6 6 6 6 4 4 . . 
. . . . f f f f f f . . . . 
. . . . f f . . f f . . . . 
`, img`
. . . . . . . . . . . . . . 
. . . . . f f f f . . . . . 
. . . f f f f f c f f . . . 
. . f f c f f f c f f f . . 
. . f c c f f f f c f f . . 
. . f c f f e e f f c f . . 
. . f f f 4 4 e e f f f . . 
. . f f d f 4 4 f d f f . . 
. . f 4 1 f 4 4 f 1 4 f . . 
. . . 4 4 4 4 4 4 4 4 . . . 
. . . . 4 4 4 4 4 4 e f . . 
. . e 4 b 2 2 2 e d d 4 . . 
. . 4 d 2 2 2 2 e d d e . . 
. . 4 4 6 6 6 6 6 e e . . . 
. . . . f f f f f f . . . . 
. . . . . . . . f f . . . . 
`, img`
. . . . . . . . . . . . . . 
. . . . . f f f f . . . . . 
. . . f f f f f c f f . . . 
. . f f c f f f c f f f . . 
. . f c c f f f f c f f . . 
. . f c f f e e f f c f . . 
. . f f f 4 4 e e f f f . . 
. . f f d f 4 4 f d f f . . 
. . f 4 1 f 4 4 f 1 4 f . . 
. . . 4 4 4 4 4 4 4 4 . . . 
. . . . 4 4 4 4 4 4 . . . . 
. . e 4 b 2 2 2 2 b 4 e . . 
. . 4 d 2 2 2 2 2 2 d 4 . . 
. . 4 4 6 6 6 6 6 6 4 4 . . 
. . . . f f f f f f . . . . 
. . . . f f . . f f . . . . 
`];
            case "anim21":return [img`
......................aaaaaaaaaa..............................
......................aaaaaaaaaa..............................
....................aaaaaaaaaaaaaa............................
....................aaaaaaaaaaaaaa............................
....................aa77aaaaaa77aa............................
....................aa77aaaaaa77aa............................
....................aaaaffaaffaaaa............................
....................aaaaffaaffaaaa............................
..................aaaaaaff11ffaaaaaa..........................
..................aaaaaaff11ffaaaaaa..........................
..................aaaa11ffffff11aaaa..........................
..................aaaa11ffffff11aaaa..........................
..................aaaaaaffffffcaaaaa..........................
..................aaaaacffffffcaaaaa..........................
..............aaaaaaaaac11ff11caaaaaaaaa......................
..............aaaaaaaaac11ff11caaaaaaaaa......................
..........aaaaaaaaaaaaccccccccccaaaaaaaaaaaaaaaa..............
..........aaaaaaaaaaaaccccccccccaaaaaaaaaaaaaaaa..............
........aaaaaacccccccaaaaacccaaaaaccccccccccaaaaaa............
........aaaaaacccccccccaaaaaaaaaccccccccccccaaaaaa............
......aaaaccccccaaaaaaccccccccccccaaaaaaaaaacccaaaaa..........
......aaaaccccccaaaaaaccccccccccccaaaaaaaaaacccaaaaa..........
......aaaaaaaaaaaaaaaaaaaaaccaaaaaaaaaccaaaaaaaaaaaaaa........
......aaaaaaaaaaaaaaaaaaaaaccaaaaaaaaaccaaaaaaaaaaaaaa........
......aaaaaaaaaaaaaaaaaaaaaccaaaaaaaaaaaaaaaaaaaaaaaaaaa......
......aaaaaaaaaccaaaaaaaaaaccaaaaaaaaaaaaaaaaaaaaaaaaaaa......
......aaaaaaaaaccaaaaaaaaaaccaaaaaaaaaaaaaaaaaaaaaaaaaaa......
......aaaaaaaaaaaaaaaaaccaaccaaaaccaaaaaaccccaaaaaaaaaaa......
....aaaaaaaa..aaaaaaaaaccaaccaaaaccaaaaaaccccaaaaaaaaaaa......
....aaaaaaaa..aaaccccaaaaaaccaaaaaaaaaaccccaaaaaaaaaaaaaaa....
....aaaaaaaa....accccaaaaaaccaaaaaaaaaaccccaaaa..aaaaaaaaa....
....aaaaaaaa....aaaacccccccccccccccccccccaaaaaa..aaaaaaaaa....
....aaaaaaaa....aaaacccccccccccccccccccccaaaa....aaaaaaaaa....
....aaaaaaaa....aaaaaaaaccaaaaaaaaaaaccaaaaaa....aaaaaaaaa....
..aaaaaaaaaaaa....aaaaaaccaaaaaaaaaaaccaaaa......aaaaaaaaaaa..
..aaaaaaaaaaaa....aaccccccaaaaaaaaaaaccaaaa....aaaaaaaaaaaaa..
..aaaaaaaaaaaa....aaccccccaaaaaaaaaaaccaaaa....aaaaaaaaaaaaa..
..aaaaaaaaaaaa....aaccaaaaaaaaaaaaaaaccaaaa....aaaaaaaaaaaaa..
aaaaaaaaaaaaaa..aaaaccaaaaaddaaaaaaaaccaaaaaa..aaaaaaaaaaaaaaa
aaaaaaaaaaaaaa..aaaaccaaaaaddaaaaaaaaccaaaaaa..aaaaaaaaaaaaaaa
aaaaaaaaaaaaaa..aaaaccaaaaaddaaddaaaaaaaaaaaa..aaaaaaaaaaaaaaa
aaaaaaaaaaaaaa..aaaaccaaaaaddaaddaaaaaaaaaaaa..aaaaaaaaaaaaaaa
aaaaaaaaaaaa....aaaaaaaaaddddddddddddaaaaaaaa..aaaaaaaaaaaaaaa
aaaaaaaaaaaa....aaaaaaaaaddddddddddddaaaaaaaa....aaaaaaaaaaaaa
..aaaaaaaaaa....aaaaaaaaa..ddddddddddaaaaaaaa....aaaaaaaaaaa..
..aaaaaaaaaa....aaaaaaaaa..ddddddddddaaaaaaaa....aaaaaaaaaaa..
..aaaaaaaaaa....aaaaaaaaa..dddddd....aaaaaaaa....aaaaaaaaaaa..
..aaaaaaaaaa....aaaaaaaaa..dddddd....aaaaaaaaaa..aaaaaaaaaaa..
....aaaaaaaa..aaaaaaaaa....dddddd......aaaaaaaa..aaaaaaaaa....
....aaaaaaaa..aaaaaaaaa....dddddd......aaaaaaaa..aaaaaaaaa....
....ccaaaa....aaaaaaaaa...ddddd........aaaaaaaa....aaaaaaa....
....ccaaaa....aaaaaaaaa...ddddd........aaaaaaaa....aaaaaaa....
..............aaaaaaaaa...ddddd........aaaaaaaa...............
..............aaaaaaaaa...ddddd........aaaaaaaa...............
....c.....aaaaaaaaaaaaa...ddddddddddd..aaaaaaaaaaa......c.....
....c.....aaaaaaaaaaaaa.....ddddddddd..aaaaaaaaaaa......cc....
...ccc..aaaaaaaaaaaaaaa.....ddddd33dd..aaaaaaaaaaaaa.....c....
....c...aaaaaaaaaaaaaaa.......ddd33dd..aaaaaaaaaaaaa.....c....
........aaaaaaaaaaaaaaa.......ddddd33..aaaaaaaaaaaaa..........
........aaaaaaaaaaaaaaa.......ddddd33..aaaaaaaaaaaaa..........
`, img`
......................aaaaaaaaaa..............................
......................aaaaaaaaaa..............................
....................aaaaaaaaaaaaaa............................
....................aaaaaaaaaaaaaa............................
....................aa77aaaaaa77aa............................
....................aa77aaaaaa77aa............................
....................aaaaffaaffaaaa............................
....................aaaaffaaffaaaa............................
..................aaaaaaff11ffaaaaaa..........................
..................aaaaaaff11ffaaaaaa..........................
..................aaaa11ffffff11aaaa..........................
..................aaaa11ffffff11aaaa..........................
..................aaaaaaffffffcaaaaa..........................
..................aaaaacffffffcaaaaa..........................
..............aaaaaaaaac11ff11caaaaaaaaa......................
..............aaaaaaaaac11ff11caaaaaaaaa......................
..........aaaaaaaaaaaaccccccccccaaaaaaaaaaaaaaaa..............
..........aaaaaaaaaaaaccccccccccaaaaaaaaaaaaaaaa..............
........aaaaaacccccccaaaaacccaaaaaccccccccccaaaaaa............
........aaaaaacccccccccaaaaaaaaaccccccccccccaaaaaa............
......aaaaccccccaaaaaaccccccccccccaaaaaaaaaacccaaaaa..........
......aaaaccccccaaaaaaccccccccccccaaaaaaaaaacccaaaaa..........
......aaaaaaaaaaaaaaaaaaaaaccaaaaaaaaaccaaaaaaaaaaaaaa........
......aaaaaaaaaaaaaaaaaaaaaccaaaaaaaaaccaaaaaaaaaaaaaa........
......aaaaaaaaaaaaaaaaaaaaaccaaaaaaaaaaaaaaaaaaaaaaaaaaa......
......aaaaaaaaaccaaaaaaaaaaccaaaaaaaaaaaaaaaaaaaaaaaaaaa......
......aaaaaaaaaccaaaaaaaaaaccaaaaaaaaaaaaaaaaaaaaaaaaaaa......
......aaaaaaaaaaaaaaaaaccaaccaaaaccaaaaaaccccaaaaaaaaaaa......
....aaaaaaaa..aaaaaaaaaccaaccaaaaccaaaaaaccccaaaaaaaaaaa......
....aaaaaaaa..aaaccccaaaaaaccaaaaaaaaaaccccaaaaaaaaaaaaaaa....
....aaaaaaaa....accccaaaaaaccaaaaaaaaaaccccaaaa..aaaaaaaaa....
....aaaaaaaa....aaaacccccccccccccccccccccaaaaaa..aaaaaaaaa....
....aaaaaaaa....aaaacccccccccccccccccccccaaaa....aaaaaaaaa....
....aaaaaaaa....aaaaaaaaccaaaaaaaaaaaccaaaaaa....aaaaaaaaa....
..aaaaaaaaaaaa....aaaaaaccaaaaaaaaaaaccaaaa......aaaaaaaaaaa..
..aaaaaaaaaaaa....aaccccccaaaaaaaaaaaccaaaa....aaaaaaaaaaaaa..
..aaaaaaaaaaaa....aaccccccaaaaaaaaaaaccaaaa....aaaaaaaaaaaaa..
..aaaaaaaaaaaa....aaccaaaaaaaaaaaaaaaccaaaa....aaaaaaaaaaaaa..
aaaaaaaaaaaaaa..aaaaccaaaaaddaaaaaaaaccaaaaaa..aaaaaaaaaaaaaaa
aaaaaaaaaaaaaa..aaaaccaaaaaddaaaaaaaaccaaaaaa..aaaaaaaaaaaaaaa
aaaaaaaaaaaaaa..aaaaccaaaaaddaaddaaaaaaaaaaaa..aaaaaaaaaaaaaaa
aaaaaaaaaaaaaa..aaaaccaaaaaddaaddaaaaaaaaaaaa..aaaaaaaaaaaaaaa
aaaaaaaaaaaa....aaaaaaaaaddddddddddddaaaaaaaa..aaaaaaaaaaaaaaa
aaaaaaaaaaaa....aaaaaaaaaddddddddddddaaaaaaaa....aaaaaaaaaaaaa
..aaaaaaaaaa....aaaaaaaaa..ddddddddddaaaaaaaa....aaaaaaaaaaa..
..aaaaaaaaaa....aaaaaaaaa..ddddddddddaaaaaaaa....aaaaaaaaaaa..
..aaaaaaaaaa....aaaaaaaaa..dddddd....aaaaaaaa....aaaaaaaaaaa..
..aaaaaaaaaa....aaaaaaaaa..dddddd....aaaaaaaaaa..aaaaaaaaaaa..
....aaaaaaaa..aaaaaaaaa....dddddd......aaaaaaaa..aaaaaaaaa....
....aaaaaaaa..aaaaaaaaa....dddddd......aaaaaaaa..aaaaaaaaa....
...cccaaaa....aaaaaaaaa...ddddd........aaaaaaaa....aaaaacc....
....ccaaaa....aaaaaaaaa...ddddd........aaaaaaaa....aaaaacc....
....c.........aaaaaaaaa...ddddd........aaaaaaaa..........c....
..............aaaaaaaaa...ddddd........aaaaaaaa...............
..........aaaaaaaaaaaaa...ddddddddddd..aaaaaaaaaaa............
....c.....aaaaaaaaaaaaa.....ddddddddd..aaaaaaaaaaa......c.....
....c...aaaaaaaaaaaaaaa.....ddddd33dd..aaaaaaaaaaaaa....cc....
...ccc..aaaaaaaaaaaaaaa.......ddd33dd..aaaaaaaaaaaaa.....c....
....c...aaaaaaaaaaaaaaa.......ddddd33..aaaaaaaaaaaaa.....c....
........aaaaaaaaaaaaaaa.......ddddd33..aaaaaaaaaaaaa..........
`, img`
......................aaaaaaaaaa..............................
......................aaaaaaaaaa..............................
....................aaaaaaaaaaaaaa............................
....................aaaaaaaaaaaaaa............................
....................aa77aaaaaa77aa............................
....................aa77aaaaaa77aa............................
....................aaaaffaaffaaaa............................
....................aaaaffaaffaaaa............................
..................aaaaaaff11ffaaaaaa..........................
..................aaaaaaff11ffaaaaaa..........................
..................aaaa11ffffff11aaaa..........................
..................aaaa11ffffff11aaaa..........................
..................aaaaaaffffffcaaaaa..........................
..................aaaaacffffffcaaaaa..........................
..............aaaaaaaaac11ff11caaaaaaaaa......................
..............aaaaaaaaac11ff11caaaaaaaaa......................
..........aaaaaaaaaaaaccccccccccaaaaaaaaaaaaaaaa..............
..........aaaaaaaaaaaaccccccccccaaaaaaaaaaaaaaaa..............
........aaaaaacccccccaaaaacccaaaaaccccccccccaaaaaa............
........aaaaaacccccccccaaaaaaaaaccccccccccccaaaaaa............
......aaaaccccccaaaaaaccccccccccccaaaaaaaaaacccaaaaa..........
......aaaaccccccaaaaaaccccccccccccaaaaaaaaaacccaaaaa..........
......aaaaaaaaaaaaaaaaaaaaaccaaaaaaaaaccaaaaaaaaaaaaaa........
......aaaaaaaaaaaaaaaaaaaaaccaaaaaaaaaccaaaaaaaaaaaaaa........
......aaaaaaaaaaaaaaaaaaaaaccaaaaaaaaaaaaaaaaaaaaaaaaaaa......
......aaaaaaaaaccaaaaaaaaaaccaaaaaaaaaaaaaaaaaaaaaaaaaaa......
......aaaaaaaaaccaaaaaaaaaaccaaaaaaaaaaaaaaaaaaaaaaaaaaa......
......aaaaaaaaaaaaaaaaaccaaccaaaaccaaaaaaccccaaaaaaaaaaa......
....aaaaaaaa..aaaaaaaaaccaaccaaaaccaaaaaaccccaaaaaaaaaaa......
....aaaaaaaa..aaaccccaaaaaaccaaaaaaaaaaccccaaaaaaaaaaaaaaa....
....aaaaaaaa....accccaaaaaaccaaaaaaaaaaccccaaaa..aaaaaaaaa....
....aaaaaaaa....aaaacccccccccccccccccccccaaaaaa..aaaaaaaaa....
....aaaaaaaa....aaaacccccccccccccccccccccaaaa....aaaaaaaaa....
....aaaaaaaa....aaaaaaaaccaaaaaaaaaaaccaaaaaa....aaaaaaaaa....
..aaaaaaaaaaaa....aaaaaaccaaaaaaaaaaaccaaaa......aaaaaaaaaaa..
..aaaaaaaaaaaa....aaccccccaaaaaaaaaaaccaaaa....aaaaaaaaaaaaa..
..aaaaaaaaaaaa....aaccccccaaaaaaaaaaaccaaaa....aaaaaaaaaaaaa..
..aaaaaaaaaaaa....aaccaaaaaaaaaaaaaaaccaaaa....aaaaaaaaaaaaa..
aaaaaaaaaaaaaa..aaaaccaaaaaddaaaaaaaaccaaaaaa..aaaaaaaaaaaaaaa
aaaaaaaaaaaaaa..aaaaccaaaaaddaaaaaaaaccaaaaaa..aaaaaaaaaaaaaaa
aaaaaaaaaaaaaa..aaaaccaaaaaddaaddaaaaaaaaaaaa..aaaaaaaaaaaaaaa
aaaaaaaaaaaaaa..aaaaccaaaaaddaaddaaaaaaaaaaaa..aaaaaaaaaaaaaaa
aaaaaaaaaaaa....aaaaaaaaaddddddddddddaaaaaaaa..aaaaaaaaaaaaaaa
aaaaaaaaaaaa....aaaaaaaaaddddddddddddaaaaaaaa....aaaaaaaaaaaaa
..aaaaaaaaaa....aaaaaaaaa..ddddddddddaaaaaaaa....aaaaaaaaaaa..
..aaaaaaaaaa....aaaaaaaaa..ddddddddddaaaaaaaa....aaaaaaaaaaa..
..aaaaaaaaaa....aaaaaaaaa..dddddd....aaaaaaaa....aaaaaaaaaaa..
..aaaaaaaaaa....aaaaaaaaa..dddddd....aaaaaaaaaa..aaaaaaaaaaa..
....aaaaaaaa..aaaaaaaaa....dddddd......aaaaaaaa..aaaaaaaaa....
....aaaaaaaa..aaaaaaaaa....dddddd......aaaaaaaa..aaaaaaaaa....
....ccaaaa....aaaaaaaaa...ddddd........aaaaaaaa....aaaaacc....
...cccaaaa....aaaaaaaaa...ddddd........aaaaaaaa....aaaaacc....
....cc........aaaaaaaaa...ddddd........aaaaaaaa..........c....
....c.........aaaaaaaaa...ddddd........aaaaaaaa..........c....
..........aaaaaaaaaaaaa...ddddddddddd..aaaaaaaaaaa............
..........aaaaaaaaaaaaa.....ddddddddd..aaaaaaaaaaa............
....c...aaaaaaaaaaaaaaa.....ddddd33dd..aaaaaaaaaaaaa....c.....
....c...aaaaaaaaaaaaaaa.......ddd33dd..aaaaaaaaaaaaa....cc....
...ccc..aaaaaaaaaaaaaaa.......ddddd33..aaaaaaaaaaaaa.....c....
....c...aaaaaaaaaaaaaaa.......ddddd33..aaaaaaaaaaaaa.....c....
`, img`
......................aaaaaaaaaa..............................
......................aaaaaaaaaa..............................
....................aaaaaaaaaaaaaa............................
....................aaaaaaaaaaaaaa............................
....................aa77aaaaaa77aa............................
....................aa77aaaaaa77aa............................
....................aaaaffaaffaaaa............................
....................aaaaffaaffaaaa............................
..................aaaaaaff11ffaaaaaa..........................
..................aaaaaaff11ffaaaaaa..........................
..................aaaa11ffffff11aaaa..........................
..................aaaa11ffffff11aaaa..........................
..................aaaaaaffffffcaaaaa..........................
..................aaaaacffffffcaaaaa..........................
..............aaaaaaaaac11ff11caaaaaaaaa......................
..............aaaaaaaaac11ff11caaaaaaaaa......................
..........aaaaaaaaaaaaccccccccccaaaaaaaaaaaaaaaa..............
..........aaaaaaaaaaaaccccccccccaaaaaaaaaaaaaaaa..............
........aaaaaacccccccaaaaacccaaaaaccccccccccaaaaaa............
........aaaaaacccccccccaaaaaaaaaccccccccccccaaaaaa............
......aaaaccccccaaaaaaccccccccccccaaaaaaaaaacccaaaaa..........
......aaaaccccccaaaaaaccccccccccccaaaaaaaaaacccaaaaa..........
......aaaaaaaaaaaaaaaaaaaaaccaaaaaaaaaccaaaaaaaaaaaaaa........
......aaaaaaaaaaaaaaaaaaaaaccaaaaaaaaaccaaaaaaaaaaaaaa........
......aaaaaaaaaaaaaaaaaaaaaccaaaaaaaaaaaaaaaaaaaaaaaaaaa......
......aaaaaaaaaccaaaaaaaaaaccaaaaaaaaaaaaaaaaaaaaaaaaaaa......
......aaaaaaaaaccaaaaaaaaaaccaaaaaaaaaaaaaaaaaaaaaaaaaaa......
......aaaaaaaaaaaaaaaaaccaaccaaaaccaaaaaaccccaaaaaaaaaaa......
....aaaaaaaa..aaaaaaaaaccaaccaaaaccaaaaaaccccaaaaaaaaaaa......
....aaaaaaaa..aaaccccaaaaaaccaaaaaaaaaaccccaaaaaaaaaaaaaaa....
....aaaaaaaa....accccaaaaaaccaaaaaaaaaaccccaaaa..aaaaaaaaa....
....aaaaaaaa....aaaacccccccccccccccccccccaaaaaa..aaaaaaaaa....
....aaaaaaaa....aaaacccccccccccccccccccccaaaa....aaaaaaaaa....
....aaaaaaaa....aaaaaaaaccaaaaaaaaaaaccaaaaaa....aaaaaaaaa....
..aaaaaaaaaaaa....aaaaaaccaaaaaaaaaaaccaaaa......aaaaaaaaaaa..
..aaaaaaaaaaaa....aaccccccaaaaaaaaaaaccaaaa....aaaaaaaaaaaaa..
..aaaaaaaaaaaa....aaccccccaaaaaaaaaaaccaaaa....aaaaaaaaaaaaa..
..aaaaaaaaaaaa....aaccaaaaaaaaaaaaaaaccaaaa....aaaaaaaaaaaaa..
aaaaaaaaaaaaaa..aaaaccaaaaaddaaaaaaaaccaaaaaa..aaaaaaaaaaaaaaa
aaaaaaaaaaaaaa..aaaaccaaaaaddaaaaaaaaccaaaaaa..aaaaaaaaaaaaaaa
aaaaaaaaaaaaaa..aaaaccaaaaaddaaddaaaaaaaaaaaa..aaaaaaaaaaaaaaa
aaaaaaaaaaaaaa..aaaaccaaaaaddaaddaaaaaaaaaaaa..aaaaaaaaaaaaaaa
aaaaaaaaaaaa....aaaaaaaaaddddddddddddaaaaaaaa..aaaaaaaaaaaaaaa
aaaaaaaaaaaa....aaaaaaaaaddddddddddddaaaaaaaa....aaaaaaaaaaaaa
..aaaaaaaaaa....aaaaaaaaa..ddddddddddaaaaaaaa....aaaaaaaaaaa..
..aaaaaaaaaa....aaaaaaaaa..ddddddddddaaaaaaaa....aaaaaaaaaaa..
..aaaaaaaaaa....aaaaaaaaa..dddddd....aaaaaaaa....aaaaaaaaaaa..
..aaaaaaaaaa....aaaaaaaaa..dddddd....aaaaaaaaaa..aaaaaaaaaaa..
....aaaaaaaa..aaaaaaaaa....dddddd......aaaaaaaa..aaaaaaaaa....
....aaaaaaaa..aaaaaaaaa....dddddd......aaaaaaaa..aaaaaaaaa....
....ccaaaa....aaaaaaaaa...ddddd........aaaaaaaa....aaaaacc....
....ccaaaa....aaaaaaaaa...ddddd........aaaaaaaa....aaaaacc....
...cc.........aaaaaaaaa...ddddd........aaaaaaaa..........c....
....cc........aaaaaaaaa...ddddd........aaaaaaaa..........c....
....c.....aaaaaaaaaaaaa...ddddddddddd..aaaaaaaaaaa.......c....
..........aaaaaaaaaaaaa.....ddddddddd..aaaaaaaaaaa............
........aaaaaaaaaaaaaaa.....ddddd33dd..aaaaaaaaaaaaa..........
c...c...aaaaaaaaaaaaaaa.......ddd33dd..aaaaaaaaaaaaa.c..c...c.
.c..c..ccaaaaaaaaaaaaaa.......ddddd33..aaaaaaaaaaaaa..c.cc.c..
...ccc..ccaaaaaaaaaaaaa.......ddddd33..aaaaaaaaaaaaa.....c....
`, img`
......................aaaaaaaaaa..............................
......................aaaaaaaaaa..............................
....................aaaaaaaaaaaaaa............................
....................aaaaaaaaaaaaaa............................
....................aa77aaaaaa77aa............................
....................aa77aaaaaa77aa............................
....................aaaaffaaffaaaa............................
....................aaaaffaaffaaaa............................
..................aaaaaaff11ffaaaaaa..........................
..................aaaaaaff11ffaaaaaa..........................
..................aaaa11ffffff11aaaa..........................
..................aaaa11ffffff11aaaa..........................
..................aaaaaaffffffcaaaaa..........................
..................aaaaacffffffcaaaaa..........................
..............aaaaaaaaac11ff11caaaaaaaaa......................
..............aaaaaaaaac11ff11caaaaaaaaa......................
..........aaaaaaaaaaaaccccccccccaaaaaaaaaaaaaaaa..............
..........aaaaaaaaaaaaccccccccccaaaaaaaaaaaaaaaa..............
........aaaaaacccccccaaaaacccaaaaaccccccccccaaaaaa............
........aaaaaacccccccccaaaaaaaaaccccccccccccaaaaaa............
......aaaaccccccaaaaaaccccccccccccaaaaaaaaaacccaaaaa..........
......aaaaccccccaaaaaaccccccccccccaaaaaaaaaacccaaaaa..........
......aaaaaaaaaaaaaaaaaaaaaccaaaaaaaaaccaaaaaaaaaaaaaa........
......aaaaaaaaaaaaaaaaaaaaaccaaaaaaaaaccaaaaaaaaaaaaaa........
......aaaaaaaaaaaaaaaaaaaaaccaaaaaaaaaaaaaaaaaaaaaaaaaaa......
......aaaaaaaaaccaaaaaaaaaaccaaaaaaaaaaaaaaaaaaaaaaaaaaa......
......aaaaaaaaaccaaaaaaaaaaccaaaaaaaaaaaaaaaaaaaaaaaaaaa......
......aaaaaaaaaaaaaaaaaccaaccaaaaccaaaaaaccccaaaaaaaaaaa......
....aaaaaaaa..aaaaaaaaaccaaccaaaaccaaaaaaccccaaaaaaaaaaa......
....aaaaaaaa..aaaccccaaaaaaccaaaaaaaaaaccccaaaaaaaaaaaaaaa....
....aaaaaaaa....accccaaaaaaccaaaaaaaaaaccccaaaa..aaaaaaaaa....
....aaaaaaaa....aaaacccccccccccccccccccccaaaaaa..aaaaaaaaa....
....aaaaaaaa....aaaacccccccccccccccccccccaaaa....aaaaaaaaa....
....aaaaaaaa....aaaaaaaaccaaaaaaaaaaaccaaaaaa....aaaaaaaaa....
..aaaaaaaaaaaa....aaaaaaccaaaaaaaaaaaccaaaa......aaaaaaaaaaa..
..aaaaaaaaaaaa....aaccccccaaaaaaaaaaaccaaaa....aaaaaaaaaaaaa..
..aaaaaaaaaaaa....aaccccccaaaaaaaaaaaccaaaa....aaaaaaaaaaaaa..
..aaaaaaaaaaaa....aaccaaaaaaaaaaaaaaaccaaaa....aaaaaaaaaaaaa..
aaaaaaaaaaaaaa..aaaaccaaaaaddaaaaaaaaccaaaaaa..aaaaaaaaaaaaaaa
aaaaaaaaaaaaaa..aaaaccaaaaaddaaaaaaaaccaaaaaa..aaaaaaaaaaaaaaa
aaaaaaaaaaaaaa..aaaaccaaaaaddaaddaaaaaaaaaaaa..aaaaaaaaaaaaaaa
aaaaaaaaaaaaaa..aaaaccaaaaaddaaddaaaaaaaaaaaa..aaaaaaaaaaaaaaa
aaaaaaaaaaaa....aaaaaaaaaddddddddddddaaaaaaaa..aaaaaaaaaaaaaaa
aaaaaaaaaaaa....aaaaaaaaaddddddddddddaaaaaaaa....aaaaaaaaaaaaa
..aaaaaaaaaa....aaaaaaaaa..ddddddddddaaaaaaaa....aaaaaaaaaaa..
..aaaaaaaaaa....aaaaaaaaa..ddddddddddaaaaaaaa....aaaaaaaaaaa..
..aaaaaaaaaa....aaaaaaaaa..dddddd....aaaaaaaa....aaaaaaaaaaa..
..aaaaaaaaaa....aaaaaaaaa..dddddd....aaaaaaaaaa..aaaaaaaaaaa..
....aaaaaaaa..aaaaaaaaa....dddddd......aaaaaaaa..aaaaaaaaa....
....aaaaaaaa..aaaaaaaaa....dddddd......aaaaaaaa..aaaaaaaaa....
....ccaaaa....aaaaaaaaa...ddddd........aaaaaaaa....aaaaacc....
....ccaaaa....aaaaaaaaa...ddddd........aaaaaaaa....aaaaacc....
....c.........aaaaaaaaa...ddddd........aaaaaaaa.........c.....
...cc.........aaaaaaaaa...ddddd........aaaaaaaa.........cc....
....cc....aaaaaaaaaaaaa...ddddddddddd..aaaaaaaaaaa.......c....
....c.....aaaaaaaaaaaaa.....ddddddddd..aaaaaaaaaaa.......c....
........aaaaaaaaaaaaaaa.....ddddd33dd..aaaaaaaaaaaaa..........
........aaaaaaaaaaaaaaa.......ddd33dd..aaaaaaaaaaaaa..........
.c..c...aaacaaaaaaaaaaa.......ddddd33..aaaaaaaaaaaaa.c..c...c.
..c.c...cccaaaaaaaaaaaa.......ddddd33..aaaaaaaaaaaaa..c.cc.c..
`];
            case "anim22":return [img`
. . . . . . . . . . . . . . . . 
. . 4 . . . 4 . . . . . . . . . 
. 4 f 4 d 4 f 4 . . . . . . . . 
. 4 f 4 4 4 f 4 . . . . . . . . 
. 4 4 d 4 d 4 4 . . . . . . . . 
. e 4 f 4 f 4 e . . . . e 4 f . 
. e 4 4 4 4 4 4 d . . . e 4 f . 
f d 4 4 4 4 4 d d e e e 4 4 4 . 
. . d d d 4 f d 4 4 4 4 4 4 . . 
. . . d d f f d d 4 4 4 4 4 4 . 
. . . . . d d d 4 4 f 4 f 4 4 . 
. . . . . . d 4 d 4 f f f d d . 
. . . . . . f . . . . . . . f . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . 4 . . . 4 . . . . . . . . . 
. 4 f 4 d 4 f 4 . . . . . . . . 
. 4 f 4 4 4 f 4 . . . . . . . . 
. 4 4 d 4 d 4 4 . . . . . . . . 
. e 4 f 4 f 4 e . . . . e 4 f . 
. e 4 4 4 4 4 4 d . . . e 4 f . 
f d 4 4 4 4 4 d d e e e 4 4 4 . 
. . d d d 4 f d 4 4 4 4 4 4 . . 
. . . d d f f d d 4 4 4 4 4 4 . 
. . . . . d d d 4 4 f 4 f 4 4 . 
. . . . . d d 4 d 4 f f f 4 d . 
. . . . f d 4 . . . . . . . d . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . 4 . . . 4 . . . . . . . . . 
. 4 f 4 d 4 f 4 . . . . . . . . 
. 4 f 4 4 4 f 4 . . . . . . . . 
. 4 4 d 4 d 4 4 . . . . . . . . 
. e 4 d 4 d 4 e . . . . e 4 f . 
. e 4 4 4 4 4 4 d . . . e 4 f . 
f d 4 4 4 4 4 d d e e e 4 4 4 . 
. . d d d 4 f d 4 4 4 4 4 4 . . 
. . . d d f f d d 4 4 4 4 4 4 . 
. . . . . d d d 4 4 f 4 f 4 4 . 
. . . . . . d 4 d 4 f f f d d . 
. . . . . . f . . . . . . . f . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . 4 . . . 4 . . . . . . . . . 
. 4 f 4 d 4 f 4 . . . . . . . . 
. 4 f 4 4 4 f 4 . . . . . . . . 
. 4 4 d 4 d 4 4 . . . . . . . . 
. e 4 f 4 f 4 e . . . . e 4 f . 
. e 4 4 4 4 4 4 d . . . e 4 f . 
f d 4 4 4 4 4 d d e e e 4 4 4 . 
. . d d d 4 f d 4 4 4 4 4 4 . . 
. . . d d f f d d 4 4 4 4 4 4 . 
. . . . . d d d 4 4 f 4 f 4 4 . 
. . . . . d d 4 d 4 f f f 4 d . 
. . . . f d 4 . . . . . . . d . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . 4 . . . 4 . . . . . . . . . 
. 4 f 4 d 4 f 4 . . . . . . . . 
. 4 f 4 4 4 f 4 . . . . . . . . 
. 4 4 d 4 d 4 4 . . . . . . . . 
. e 4 f 4 f 4 e . . . . e 4 f . 
. e 4 4 4 4 4 4 d . . . e 4 f . 
f d 4 4 4 4 4 d d e e e 4 4 4 . 
. . d d d 4 f d 4 4 4 4 4 4 . . 
. . . d d f f d d 4 4 4 4 4 4 . 
. . . . . d d d 4 4 f 4 f 4 4 . 
. . . . . . d 4 d 4 f f f d d . 
. . . . . . f . . . . . . . f . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . 4 . . . 4 . . . . . . . . . 
. 4 f 4 d 4 f 4 . . . . . . . . 
. 4 f 4 4 4 f 4 . . . . . . . . 
. 4 4 d 4 d 4 4 . . . . . . . . 
. e 4 f 4 f 4 e . . . . e 4 f . 
. e 4 4 4 4 4 4 d . . . e 4 f . 
f d 4 4 4 4 4 d d e e e 4 4 4 . 
. . d d d 4 f d 4 4 4 4 4 4 . . 
. . . d d f f d d 4 4 4 4 4 4 . 
. . . . . d d d 4 4 f 4 f 4 4 . 
. . . . . d d 4 d 4 f f f 4 d . 
. . . . f d 4 . . . . . . . d . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`];
        }
        return null;
    })

}
// Auto-generated code. Do not edit.
